version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "create-orders-endpoint"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-6ge24nirg7k8"
s3_prefix = "create-orders-endpoint"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TableName=\"orders\""
image_repositories = [
    "CreateOrdersFunction=084882962555.dkr.ecr.us-west-2.amazonaws.com/create-orders-endpoint",
    "GetOrderFunction=084882962555.dkr.ecr.us-west-2.amazonaws.com/get-orders-endpoint"
]
