version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "orders-api-prod"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-6ge24nirg7k8"
s3_prefix = "orders-api-prod"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
    "TableName=orders_prod",
    "OrderStatusUpdateTopicName=order_status_update_topic_prod"
]
image_repositories = [
    "CreateOrdersFunction=084882962555.dkr.ecr.us-west-2.amazonaws.com/create-orders-endpoint",
    "GetOrderFunction=084882962555.dkr.ecr.us-west-2.amazonaws.com/get-orders-endpoint",
    "PatchOrderFunction=084882962555.dkr.ecr.us-west-2.amazonaws.com/patch-order-endpoint",
    "RecordProcessor=084882962555.dkr.ecr.us-west-2.amazonaws.com/orders-db-stream-processor"
]
