AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  create-orders-endpoint

  Endpoint responsible for creating order resources
  
Globals:
  Function:
    Timeout: 3

Resources:
  CreateOrdersFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: ECR URL
      Events:
        Api:
          Type: Api
          Properties:
            Path: /hello-world/{id}
            Method: get
    Metadata:
      DockerTag: nodejs14.x-v1
      DockerContext: .
      Dockerfile: Dockerfile

Outputs:
  CreateOrdersFunction:
    Description: "Function ARN"
    Value: !GetAtt CreateOrdersFunction.Arn
  CreateOrdersFunctionIamRole:
    Description: "Implicit IAM Role created for function"
    Value: !GetAtt CreateOrdersFunction.Arn
